######################################################################
# Automatically generated by qmake (2.01a) qui jul 23 14:57:46 2015
######################################################################

TEMPLATE = app
TARGET = serverInterface
DEPENDPATH += .
INCLUDEPATH += .

# Input
CONFIG += qt debug
HEADERS += dialog.h
SOURCES += dialog.cpp serverInterface.cpp
